name: Build Kernel poplar_dsds
on:
  push:
    branches:    
      - makiras

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Init Repo
      run: |
        cd ~
        git clone https://github.com/Makiras/poplar_dsds.git -b makiras --depth=1 
    - name: Build With Shell
      run: |
        cd ~/poplar_dsds
        bash build_full.sh
    - name: Package With AnyKernel
      run: |
        cd ~
        cp poplar_dsds/AnyKernel ./ -r
        cd AnyKernel/
        cp ../poplar_dsds/out/arch/arm64/boot/Image.gz-dtb  ./
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: blu_spark_makiras_modified.zip
        path: /home/runner/AnyKernel/
